### PR TITLE
Issue/97

### PR DESCRIPTION
**Pull request by c-ro**
Replaced the original question/answers with the five buttons.  Right now the 'docs' are in index.html and appear as modals when user clicks a button.  Not sure this was the right way to go about things but have saved the html formatted docs individually in /src/templates should somebody want to take it another direction.

### CODE REVIEW

**Comment by chaserx** [comment]
thanks @c-ro !! 

I'll pull this down and check it out tonight! :rocket:

**Comment by chaserx** [comment]
@c-ro I've sent a screencast of your work to one of our stakeholders to get their feedback. Hang tight.

**Comment by eeeschwartz** [comment]
Thanks for the help @c-ro. So long as @chaserx is good, I can merge.

The caveat to this approach is that the facilities are static, so anytime this content needs to be updated our stakeholders will go through us. Before long we'll want to make these facilities part of the Google spreadsheet-driven approach used by outpatient and residential.

**Comment by chaserx** [comment]
I don't have any objection here other than the caveat mentioned previously. 

+1

**Comment by c-ro** [comment]
Ah, of course.  I'll need to catch up on the Google Docs approach.  Do you have any recommended reading aside from the link in the readme?

**Comment by eeeschwartz** [comment]
@c-ro I took a crack at improving the developer documentation in #113. Definitely give a holler with any snags and we'll to improve. 

Thanks again for jumping in!

**Comment by c-ro** [comment]
Thanks @eeeschwartz, this is definitely helpful!

**Pull request merged**
